name: payfast
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
dependencies: {crypto: ^3.0.2}
